config/routes.rb
Rails.application.routes.draw do
  # home page for normal users and unauthenticated users
 

  devise_for :admins
  
  # set an admin home page at 'admin' action, 'home' controller
  authenticated :admin do
    root :to => "home#admin", as: :admin_root
  end

  root "home#page"
  
  # do not create users/sessions routes
  devise_for :users, skip: [:sessions]
  as :user do
    # custom path to login/sign_in
    get '/sign_in', to: 'users/sessions#new', as: :new_user_session
    post '/sign_in', to: 'users/sessions#create', as: :user_session
    # custom path to sign_out
    delete '/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  
  resources :profiles
  # add a custom /profile route to 'show' and 'edit' action in profiles_controller.rb
  # get '/profile', to: 'profiles#show', as: :my_profile
  # get '/profile/edit', to: 'profiles#edit', as: :edit_my_profile

  resources :listings do
    resources :rent_requests
  end
  get '/my_requests', to: 'rent_requests#my_requests', as: :my_requests
  get '/my_listings', to: 'listings#my_listings', as: :my_listings

  resources :charges, :only => [:index, :create, :new]
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :rent_requests, dependent: :destroy
  validates :title, 
            :length => { maximum: 25, too_long: "Please provide a brief title" }, 
            :presence => true
  validates :rate, :deposit,
            :numericality => { greater_than_or_equal_to: 0 }
  validates :description, :photo, :date_from, :date_to,
            :presence => true
  validate  :end_date_after_start_date?
  validate  :minimum_duration?

  def end_date_after_start_date?
    if date_to < date_from
      errors.add(:date_to, "End date must be after the start date")
    end
  end
  def minimum_duration?
    if date_to == date_from
      errors.add(:date_to, "The minimum duration is 1 day")
    end
  end
  mount_uploader :photo, PhotoUploader    
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # every action involving listings, except 'show', requires the user/admin to be logged in
  before_action :authenticate, except: [:show]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  # before_action :detach_associated, only: [:destroy]
 
  # GET /listings
  # GET /listings.json
  def index
    # only allow admins to view the index page for listings (with CRUD rights)
    unless admin_signed_in?
      no_access
    end
    # order the listings for ADMIN view (users access listings list in home page)
    @listings = Listing.all.order(created_at: :asc)
  end

  def my_listings
    # here we define @listings for each user's profile view (when logged in)
    @listings = Listing.where(:user_id => current_user.id)
  end
  
  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
    unless admin_signed_in? || (@listing.user_id == current_user.id)
      no_access
    end
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to admin_redirect, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to admin_redirect, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to admin_redirect, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # request logging in for all operations with listings (except 'show')
    def authenticate
      unless user_signed_in? || admin_signed_in?
        redirect_to new_user_session_url
      end
    end
    
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def admin_redirect
      if admin_signed_in?
        path = listing_url(@listing)
      else
        path = my_listings_url
      end
      return path
    end

    def no_access
      redirect_to root_path
      flash[:notice] = "Can't touch dis!"
    end

    # def detach_associated
    #   @listing.rent_requests.update_all(:listing_id => nil)
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :rate, :deposit, :description, :photo, :date_from, :date_to)
    end
    
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%# f.association :user %>
    <%= f.input :title %>
    <%= f.input :rate %>
    <%= f.input :deposit %>
    <%= f.input :date_from, 
                :order => [:day, :month, :year] %>
    <%= f.input :date_to, 
                :order => [:day, :month, :year] %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', listing_path(@listing) %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Listings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Owner email</th>
      <th>Title</th>
      <th>Rate</th>
      <th>Deposit</th>
      <th>Description</th>
      <th>Date from</th>
      <th>Date to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.user.email %></td>
        <td><%= listing.title %></td>
        <td><%= listing.rate %></td>
        <td><%= listing.deposit %></td>
        <td><%= listing.description %></td>
        <td><%= listing.date_from %></td>
        <td><%= listing.date_to %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/listings/indiv_index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Listings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Rate</th>
      <th>Deposit</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.rate %></td>
        <td><%= listing.deposit %></td>
        <td><%= listing.description %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/listings/my_listings.html.erb
<p id="notice"><%= notice %></p>

<h1>My Listings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Rate</th>
      <th>Deposit</th>
      <th>Description</th>
      <th>Date from</th>
      <th>Date to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.rate %></td>
        <td><%= listing.deposit %></td>
        <td><%= listing.description %></td>
        <td><%= listing.date_from %></td>
        <td><%= listing.date_to %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>By:</strong>
  <%= link_to "#{@listing.user.profile.first_name || @listing.user.profile.company_name}", profile_url(@listing.user.profile.id) %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @listing.rate %>
</p>

<p>
  <strong>Deposit:</strong>
  <%= @listing.deposit %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Date from:</strong>
  <%= @listing.date_from %>
</p>

<p>
  <strong>Date to:</strong>
  <%= @listing.date_to %>
</p>

<p>
    <strong>Photo:</strong>
    <br>
    <%= image_tag(@listing.photo_url, width: "30%", height:"30%")%>
</p>
<% if admin_signed_in? || (user_signed_in? && (@listing.user_id == current_user.id)) %>
  <%= link_to 'Edit', edit_listing_path(@listing) %>
  | <%= link_to 'Requests for this item', listing_rent_requests_path(@listing) %>
<% else %>
  <%= link_to 'Rent', new_listing_rent_request_path(@listing) %>
<% end %>