config/routes.rb
Rails.application.routes.draw do
  # home page for normal users and unauthenticated users
 

  devise_for :admins
  
  # set an admin home page at 'admin' action, 'home' controller
  authenticated :admin do
    root :to => "home#admin", as: :admin_root
  end

  root "home#page"
  
  # do not create users/sessions routes
  devise_for :users, skip: [:sessions]
  as :user do
    # custom path to login/sign_in
    get '/sign_in', to: 'users/sessions#new', as: :new_user_session
    post '/sign_in', to: 'users/sessions#create', as: :user_session
    # custom path to sign_out
    delete '/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  
  resources :profiles
  # add a custom /profile route to 'show' and 'edit' action in profiles_controller.rb
  # get '/profile', to: 'profiles#show', as: :my_profile
  # get '/profile/edit', to: 'profiles#edit', as: :edit_my_profile

  resources :listings do
    resources :rent_requests
  end
  get '/my_requests', to: 'rent_requests#my_requests', as: :my_requests
  get '/my_listings', to: 'listings#my_listings', as: :my_listings

  resources :charges, :only => [:index, :create, :new]
end

app/views/layouts/_navbar.html.erb
<%# Add Pure horizontal menu to newly created _navbar.html.erb (in views/layouts): %>
<%# https://purecss.io/menus/ %>
<div class="pure-menu pure-menu-horizontal">
    <a href="/" class="pure-menu-heading pure-menu-link">Whybuy</a>
    <ul class="navbar-btns pure-menu-list">
    <!-- if user is signed in - show Log Out button -->
    <% if user_signed_in? %> 
        <!-- prompt user to create a profile if they dont have one-->
        <% if current_user.profile.nil? %>
            <li class="pure-menu-item">
                <%= link_to 'Create Profile', new_profile_path, class: "pure-menu-link" %>
            </li>
            <li class="pure-menu-item">
                <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "pure-menu-link" %>
            </li>
        <!-- otherwise, show a link to user's profile page-->
        <% else %>      
            <li class="pure-menu-item">
                <%= link_to "Add a Listing", new_listing_path, class: "pure-menu-link" %>
            </li>
            <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
                <a id="menuLink1" class="pure-menu-link">
                    <%= current_user.email %>
                </a>
                <ul class="pure-menu-children">
                    <li class="pure-menu-item">
                        <%= link_to "My Profile", profile_path(current_user.profile.id), class: "pure-menu-link" %>
                    </li>
                    <li class="pure-menu-item">
                        <%= link_to "My Listings", my_listings_path, class: "pure-menu-link" %>
                    </li>
                    <li class="pure-menu-item">
                        <%= link_to "My Requests", my_requests_path, class: "pure-menu-link" %>
                    </li>
                    <li class="pure-menu-item">
                        <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "pure-menu-link" %>
                    </li>
                </ul>
            </li>
        <% end %>
    <% elsif admin_signed_in? %>
        <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
            <a id="menuLink1" class="pure-menu-link">
                Admin Dashboard
            </a>
            <ul class="pure-menu-children">
                <li class="pure-menu-item">
                    <%= link_to 'Profiles', profiles_path, class: "pure-menu-link" %>
                </li>
                <li class="pure-menu-item">
                    <%= link_to 'Listings', listings_path, class: "pure-menu-link" %>
                </li>
                <li class="pure-menu-item">
                    <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "pure-menu-link" %>
                </li>
            </ul>
        </li>
    <!-- if user not signed in - show Sign Up and Log In buttons -->
    <% else %>
        <li class="pure-menu-item"><%= link_to "Sign up", new_user_registration_path, class: "pure-menu-link" %></li>
        <li class="pure-menu-item"><%= link_to 'Log In', new_user_session_path, class: "pure-menu-link" %></li>
    <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhybuyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/navbar' %>
    <!-- Add side margins to whole app's content except navbar-->
    <div class="container">
      <%# this is where views from other controllers are rendered %>
      <%= yield %>
      <%# moving JS to the end of body to improve performance %>
    </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
  <script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>
   <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>