config/routes.rb
Rails.application.routes.draw do
  # home page for normal users and unauthenticated users
 

  devise_for :admins
  
  # set an admin home page at 'admin' action, 'home' controller
  authenticated :admin do
    root :to => "home#admin", as: :admin_root
  end

  root "home#page"
  
  # do not create users/sessions routes
  devise_for :users, skip: [:sessions]
  as :user do
    # custom path to login/sign_in
    get '/sign_in', to: 'users/sessions#new', as: :new_user_session
    post '/sign_in', to: 'users/sessions#create', as: :user_session
    # custom path to sign_out
    delete '/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  
  resources :profiles
  # add a custom /profile route to 'show' and 'edit' action in profiles_controller.rb
  # get '/profile', to: 'profiles#show', as: :my_profile
  # get '/profile/edit', to: 'profiles#edit', as: :edit_my_profile

  resources :listings do
    resources :rent_requests
  end
  get '/my_requests', to: 'rent_requests#my_requests', as: :my_requests
  get '/my_listings', to: 'listings#my_listings', as: :my_listings

  resources :charges, :only => [:index, :create, :new]
end

app/models/rent_request.rb
class RentRequest < ApplicationRecord
  belongs_to :owner, :class_name => 'User'
  belongs_to :requester, :class_name => 'User'
  belongs_to :listing
  validates :days,
            :presence => true,
            :numericality => { greater_than_or_equal_to: 1, message: "Duration is at least 1 day" }
end

app/controllers/rent_requests_controller.rb
class RentRequestsController < ApplicationController
  # every action involving rent requests, requires the user/admin to be logged in
  before_action :authenticate
  before_action :set_rent_request, only: [:show, :edit, :update, :destroy]
  # call a set_listing action before any other to determine which listing we are working with
  before_action :set_listing, except: [:my_requests]
  # GET /rent_requests
  # GET /rent_requests.json

  # index action will be used as an aggregated view for all the requests for a particular listing
  def index
    if user_signed_in? && (current_user.id != @listing.user_id)
      no_access
    else
      @rent_requests = RentRequest.where(:listing_id => @listing.id).order(created_at: :asc)
    end
    # @rent_requests = RentRequest.all.order(created_at: :asc)
  end

  # GET /rent_requests/1
  # GET /rent_requests/1.json
  def show
  end

  def my_requests
    @rent_requests = RentRequest.where(:requester_id => current_user.id).order(created_at: :asc)
  end

  # GET /rent_requests/new
  def new
    if RentRequest.where("requester_id = ? AND listing_id = ?", current_user.id, @listing.id).exists?
      redirect_to root_url
      flash[:notice] = "Already requested"
    # we instantiate RentRequest objects as children of Listing object
    elsif current_user.id == @listing.user_id
      redirect_to root_url
      flash[:notice] = "You cannot request your own item!"
    else
      @rent_request = @listing.rent_requests.new
    end
  end

  # GET /rent_requests/1/edit
  def edit
    # only allow admins and creators of requests to edit them (not even owners)
    unless admin_signed_in? || (@rent_request.requester_id == current_user.id)
      no_access
    end
  end

  # POST /rent_requests
  # POST /rent_requests.json
  def create
    # see the comment to 'new' action
    @rent_request = @listing.rent_requests.new(rent_request_params)
    # listing_id field should be the same as id of the listing we are working with
    @rent_request.listing_id = @listing.id
    # owner is determined as the user who created the listing
    @rent_request.owner_id = @listing.user.id
    # the current user is the requester
    @rent_request.requester_id = current_user.id
    @rent_request.total_price = @rent_request.days * @listing.rate

    respond_to do |format|
      if @rent_request.save
        format.html { redirect_to new_charge_url(:total_price => @rent_request.total_price), notice: 'Rent request was successfully created.' }
        format.json { render :show, status: :created, location: @rent_request }
      else
        format.html { render :new }
        format.json { render json: @rent_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rent_requests/1
  # PATCH/PUT /rent_requests/1.json
  def update
    respond_to do |format|
      if @rent_request.update(rent_request_params)
        @rent_request.total_price = @rent_request.days * @listing.rate
        @rent_request.update(rent_request_params)
        format.html { redirect_to edit_admin_redirect, notice: 'Rent request was successfully updated.' }
        format.json { render :show, status: :ok, location: @rent_request }
      else
        format.html { render :edit }
        format.json { render json: @rent_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rent_requests/1
  # DELETE /rent_requests/1.json
  def destroy
    @rent_request.destroy
    respond_to do |format|
      format.html { redirect_to admin_redirect, notice: 'Rent request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def authenticate
      unless user_signed_in? || admin_signed_in?
        redirect_to new_user_session_url
      end
    end
    
    def admin_redirect
      if admin_signed_in?
        path = listing_rent_requests_path(@listing)
      else
        path = my_requests_url
      end
      return path
    end

    def edit_admin_redirect
      if admin_signed_in?
        path = listing_rent_request_path(@listing,@rent_request)
      else
        path = my_requests_url
      end
      return path
    end

    def no_access
      redirect_to root_path
      flash[:notice] = "Can't touch dis!"
    end

    def set_rent_request
      @rent_request = RentRequest.find(params[:id])
    end

    # define a listing we are working with (used in before callback)
    def set_listing
      @listing = Listing.find(params[:listing_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rent_request_params
      params.require(:rent_request).permit(:days)
    end
end

app/helpers/rent_requests_helper.rb
module RentRequestsHelper
end

app/views/rent_requests/_edit_form.html.erb
<%= simple_form_for(@rent_request, url: listing_rent_request_path(@listing,@rent_request)) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :days,
                :label => "I want to rent it for",
                :placeholder => "days" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rent_requests/_form.html.erb
<%= simple_form_for(@rent_request, url: listing_rent_requests_path(@listing)) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :days,
                :label => "I want to rent it for",
                :placeholder => "days" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rent_requests/charge.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Your payment to "
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/rent_requests/edit.html.erb
<h1>Editing Rent Request</h1>

<%= render 'edit_form', rent_request: @rent_request %>

<%= link_to 'Show', listing_rent_request_path(@listing,@rent_request) %> 

app/views/rent_requests/index.html.erb
<p id="notice"><%= notice %></p>
<% if admin_signed_in?%>
  <h1>Requests for This Item</h1>
<% else %>
  <h1>Requests for Your Items</h1>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Requested by</th>
      <th>Duration</th>
      <th>Total price</th>
      <th>Accepted?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rent_requests.each do |rent_request| %>
      <tr>
        <td><%= rent_request.requester.email %></td>
        <td><%= rent_request.days %> days</td>
        <td>$<%= rent_request.total_price %> AUD</td>
        <td><%= rent_request.accepted %></td>
        <td><%= link_to 'Show', listing_rent_request_path(@listing,rent_request) %></td>
        <% if admin_signed_in? %>
          <td><%= link_to 'Edit', edit_listing_rent_request_path(@listing,rent_request) %></td>
          <td><%= link_to 'Destroy', listing_rent_request_path(@listing,rent_request), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rent_requests/my_requests.html.erb
<p id="notice"><%= notice %></p>

<h1>My requests</h1>

<table class="table">
  <thead>
    <tr>
      <th>Item</th>
      <th>Owned by</th>
      <th>Duration</th>
      <th>Total price</th>
      <th>Accepted?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rent_requests.each do |rent_request| %>
      <tr>
      <% listing = Listing.find(rent_request.listing_id)%>
        <td><%= listing.title %></td>
        <td><%= rent_request.owner.email %></td>
        <td><%= rent_request.days %> days</td>
        <td>$<%= rent_request.total_price %> AUD</td>
        <td><%= rent_request.accepted %></td>
        <td><%= link_to 'Show', listing_rent_request_path(listing,rent_request) %></td>
        <td><%= link_to 'Edit', edit_listing_rent_request_path(listing,rent_request) %></td>
        <td><%= link_to 'Destroy', listing_rent_request_path(listing,rent_request), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rent_requests/new.html.erb
<h1>New Rent Request</h1>

<%= render 'form', rent_request: @rent_request %>

app/views/rent_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= link_to @rent_request.listing.title, listing_path(@rent_request.listing) %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @rent_request.owner.email %>
</p>

<p>
  <strong>Requester:</strong>
  <%= @rent_request.requester.email %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @rent_request.days %> days
</p>

<p>
  <strong>Rate:</strong>
  $<%= @rent_request.listing.rate %> AUD per day
</p>

<p>
  <strong>Total price:</strong>
  $<%= @rent_request.total_price %> AUD
</p>

<p>
  <strong>Accepted:</strong>
  <%= @rent_request.accepted %>
</p>